# /docs/fun.md

- name: Installing Fun Programs
  hosts: localhost
  become: true
  tasks:
    - name: Install SL
      package: name=sl state=present
    - name: Install Cowsay
      package: name=cowsay state=present
    - name: Install lolcat
      package: name=lolcat state=present
