# Documentation: /docs/main.md
- name: Create Users
  hosts: localhost
  become: true
  roles:
    - ecommerce
  tasks:
    - name: Ensure admin account exists
      ansible.builtin.user:
        name: admin
        groups: sudo
        state: present

    - name: Ensure developer accounts exist 
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - dev1
        - dev2

    - name: Install Grafana Instance and Run it
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        published_ports:
          - "3000:3000"

